version: "2"
services:
  webapp:
    build:
      context: .
    ports:
      - 8750:80
    container_name: webapp
    volumes:
      - ./symfony:/var/www/html
      - ./vhost/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      XDEBUG_CONFIG: remote_host=192.168.0.94
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3400:3306
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: